[package]
name = "percentile-ps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

hdrhistogram = "7.5.4"
clap = { version = "4", features = ["derive", "cargo"]}
eyre = "0.6.12"
